name: Node.js Package

on: 
  push:
    branches:
      - main

jobs:
  build:
      runs-on: ubuntu-latest

      name: eslint-testing

      steps:

        - uses: actions/checkout@v3

        - uses: bahmutov/npm-install@v1

        - run: npm run lint

        - run: npm run test
